// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newinfosoft.Historytd.Repository;

namespace Newinfosoft.Historytd.Repository.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20190502015442_AddPerson")]
    partial class AddPerson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Newinfosoft.Historytd.Entity.EventBase", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abstract")
                        .HasMaxLength(500);

                    b.Property<int>("BeginDate");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EndDate");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("EventId");

                    b.HasIndex("BeginDate")
                        .HasName("IDX_BASIC_EVENT_DATE");

                    b.ToTable("T_BASIC_EVENT");
                });

            modelBuilder.Entity("Newinfosoft.Historytd.Entity.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abstract")
                        .HasMaxLength(500);

                    b.Property<int?>("Birthday");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Deathday");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<string>("HeadImage")
                        .HasMaxLength(200);

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("FamilyName")
                        .HasName("IDX_BASIC_PERSON_NAME");

                    b.HasIndex("Birthday", "Deathday")
                        .HasName("IDX_BASIC_PERSON_DATE");

                    b.ToTable("T_BASIC_PERSON");
                });
#pragma warning restore 612, 618
        }
    }
}
